import { z } from 'zod';

/**
 * QuestionPaper — the LLM output contract, rendered as a printable exam paper
 * (the Figma "Assignment Output" screen).
 *
 * The worker must produce and Zod-validate this (with one repair retry) before
 * it is persisted and shown. The academic content (title, subject, class,
 * sections, questions, answer key) is generated by the model from the uploaded
 * material; the school identity (`schoolName`, `schoolAddress`) is injected by
 * the backend from the logged-in school context. Every field is constrained so
 * a malformed generation is rejected rather than displayed.
 */

export const DifficultySchema = z.enum(['easy', 'moderate', 'challenging']);
export type Difficulty = z.infer<typeof DifficultySchema>;

export const QuestionSchema = z.object({
  text: z.string().min(1),
  difficulty: DifficultySchema,
  marks: z.number().int().positive(),
  /** Model answer for the question; collated into the paper's Answer Key. */
  answer: z.string().min(1).optional(),
});
export type Question = z.infer<typeof QuestionSchema>;

export const SectionSchema = z.object({
  title: z.string().min(1),
  instruction: z.string().optional(),
  questions: z.array(QuestionSchema).min(1),
});
export type Section = z.infer<typeof SectionSchema>;

/** Blank fill-in fields rendered at the top of the printed paper. */
export const StudentInfoSchema = z.object({
  name: z.string().optional(),
  rollNumber: z.string().optional(),
  section: z.string().optional(),
});
export type StudentInfo = z.infer<typeof StudentInfoSchema>;

export const QuestionPaperSchema = z.object({
  title: z.string().min(1),
  schoolName: z.string().min(1),
  schoolAddress: z.string().optional(),
  subject: z.string().min(1),
  className: z.string().min(1),
  totalMarks: z.number().int().positive(),
  durationMinutes: z.number().int().positive().optional(),
  generalInstructions: z.string().optional(),
  studentInfo: StudentInfoSchema,
  sections: z.array(SectionSchema).min(1),
});
export type QuestionPaper = z.infer<typeof QuestionPaperSchema>;

/**
 * GeneratedPaper — the academic subset the LLM produces. School identity
 * (schoolName/schoolAddress) is merged in by the backend after generation, so
 * the model never needs to know the institution.
 */
export const GeneratedPaperSchema = QuestionPaperSchema.omit({
  schoolName: true,
  schoolAddress: true,
});
export type GeneratedPaper = z.infer<typeof GeneratedPaperSchema>;
