import { QuestionPaperSchema, type QuestionPaper } from '@vedaai/shared';

/**
 * Phase 2 walking-skeleton stub generator.
 *
 * Produces a deterministic, schema-valid {@link QuestionPaper} without calling
 * an LLM. It exists only to prove the queue → worker → socket rails end-to-end;
 * Phase 4 replaces it with the real Gemini-backed generation. The output is
 * Zod-parsed here so the skeleton fails loudly if the frozen contract drifts.
 */
export function buildStubPaper(assignmentId: string): QuestionPaper {
  return QuestionPaperSchema.parse({
    title: `Stub Assessment ${assignmentId}`,
    subject: 'Walking Skeleton',
    totalMarks: 10,
    durationMinutes: 30,
    generalInstructions: 'This is a stub paper generated by the Phase 2 skeleton worker.',
    studentInfo: {},
    sections: [
      {
        title: 'Section A',
        instruction: 'Answer all questions.',
        questions: [
          { text: 'What does this skeleton prove traverses every layer?', difficulty: 'easy', marks: 4 },
          { text: 'Name the queue technology backing the generation pipeline.', difficulty: 'moderate', marks: 6 },
        ],
      },
    ],
  });
}
