import { QuestionPaperSchema, type QuestionPaper } from '@vedaai/shared';
import { SCHOOL_ADDRESS, SCHOOL_NAME } from '../lib/school';

/**
 * Phase 2 walking-skeleton stub generator.
 *
 * Produces a deterministic, schema-valid {@link QuestionPaper} without calling
 * an LLM. It exists only to prove the queue → worker → socket rails end-to-end;
 * Phase 4 replaces it with the real Gemini-backed generation. The output is
 * Zod-parsed here so the skeleton fails loudly if the frozen contract drifts.
 */
export function buildStubPaper(assignmentId: string): QuestionPaper {
  return QuestionPaperSchema.parse({
    title: `Stub Assessment ${assignmentId}`,
    schoolName: SCHOOL_NAME,
    schoolAddress: SCHOOL_ADDRESS,
    subject: 'Walking Skeleton',
    className: 'Class 10',
    totalMarks: 10,
    durationMinutes: 30,
    generalInstructions: 'This is a stub paper generated by the Phase 2 skeleton worker.',
    studentInfo: {},
    sections: [
      {
        title: 'Section A',
        instruction: 'Answer all questions.',
        questions: [
          {
            text: 'What does this skeleton prove traverses every layer?',
            difficulty: 'easy',
            marks: 4,
            answer: 'It proves the queue → worker → socket pipeline is fully wired.',
          },
          {
            text: 'Name the queue technology backing the generation pipeline.',
            difficulty: 'moderate',
            marks: 6,
            answer: 'BullMQ (backed by Redis).',
          },
        ],
      },
    ],
  });
}
